# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0cfa979923c618357ab275740f10375dbcaf1623ff8e2ba1f0f7ec35948dba4deaf7b7ce3d06758ec32899a65ca342b36b13e590afd14081a56e44242f55804

test:
  secret_key_base: 0bc5fe7f0487913e18aa543de1ab86180e62dc178513470b6fe3fb22629d730bb3d9a2c621b7b0d1507b91925645f9626be680f957ffedf2c07d3c5e66cff446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
